
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: omckonrails-dev
  username: dev
  password: dev
  host: <%= ENV['PG_PORT_5432_TCP_ADDR'] %>

test:
  <<: *default
  host: localhost
  database: omckonrails-test
  username: test
  password: test1

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
